### ISSUE TITLE
Incorrect git build instructions

### ISSUE THREAD

**Issue by oregonpillow** [rapier1/hpn-ssh#103]
https://github.com/rapier1/hpn-ssh/blob/1f72ea21da03cdbe94705908eda584171474c3a0/README.md?plain=1#L63-L69

`openssh-portable` DNE.

**Comment by rapier1** [comment]
Oh man, I missed that when I changed the repo name. Thank you for pointing it out and I apologize for this taking so long to respond. It's been a very busy few weeks.

**Comment by rapier1** [comment]
Pushed to master. Tag updated.
