### ISSUE TITLE
Incorrect path in HPNSSHInstallation.txt

### ISSUE THREAD

**Issue by oregonpillow** [rapier1/hpn-ssh#104]
https://github.com/rapier1/hpn-ssh/blob/52bc5fd19cb532ab4262389165ae529779004b03/HPNSSHInstallation.txt#L130

should be `/etc/default/hpnsshd`

**Comment by rapier1** [comment]
Fixed and will push shortly. Thanks again! I really do appreciate you taking the time to let me know.
