### ISSUE TITLE
ssh banner seems not to follow RFC

### ISSUE THREAD

**Issue by lapo-luchini** [rapier1/hpn-ssh#97]
The current ssh banner defined in [ssh_api.c:423](https://github.com/rapier1/hpn-ssh/blob/52bc5fd19cb532ab4262389165ae529779004b03/ssh_api.c#L423) is this:

```c
sshbuf_putf(banner, "SSH-2.0-%.100s\r\n", SSH_RELEASE)
```

and the constant is defined in [version.h:3-7](https://github.com/rapier1/hpn-ssh/blob/52bc5fd19cb532ab4262389165ae529779004b03/version.h#L3) as:

```c
#define SSH_VERSION	"OpenSSH_9.7"
#define SSH_PORTABLE	"p1"
#define SSH_HPN         "-hpn18.4.2"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE SSH_HPN
```

thus leading to a banner of: `SSH-2.0-OpenSSH_9.7p1-hpn18.4.2`.

Unfortunately it seems that [RFC4253 4.2](https://datatracker.ietf.org/doc/html/rfc4253#section-4.2) defines the banner as:

```
SSH-protoversion-softwareversion SP comments CR LF
```

> Both the 'protoversion' and 'softwareversion' strings MUST consist of
   printable US-ASCII characters, with the exception of whitespace
   characters and the minus sign (-).

thus I defined the regexp to match that in my [blackbox_exporter template](https://github.com/prometheus/blackbox_exporter/pull/1284) as `^SSH-2.0-([^ -]+)(?: (.*))?$` which turns out to fail on hpn-ssh for the forementioned reason.

Now, I can certainly relax my regexp to avoid excluding the `-`… but I thought you might want to know this (and maybe decide to prefix that with an underscore instead of an hyphen?).

**Comment by rapier1** [comment]
Well, it's annoying that I didn't pick up on that in the RFC. I'll be modifying the version string for the next release. An underscore should work but I'll need to verify that. Thanks for bringing this to our attention.

**Comment by lapo-luchini** [comment]
e.g. OpenSSH uses `SSH-2.0-OpenSSH_9.5` so an underscore should be fine.

**Comment by rapier1** [comment]
I agree, I just need to make sure it works with the compatibility tests I use in the HPN-SSH code itself. I haven't had a chance to look at that specific code portion as of yet.

**Comment by rapier1** [comment]
Resolved and will be pushed out in the new version.
